### ISSUE TITLE
Can't sign up new users

### ISSUE THREAD

**Issue by NinjuDev** [NoErrorStudio/Nexus#19]
### Describe the bug
Cannot create new users. No errors anywhere, just "Something went wrong" on the signup page. Everything is configured correctly.

### To Reproduce

1. Logout if you're currently logged in
2. Go to sign up page to create a new account
3. Fill in details of a non-existing account
4. Press "Let me in"
5. Error message appears in the verification screen or you get stuck in an infinite loop of getting a new verification email whenever you enter the code and click enter

### Expected behavior
Expected to sign up a new user without hassle.

### Screenshots
![image](https://github.com/NoErrorStudio/Nexus/assets/128250644/9af0e0a4-13e8-4053-b206-92058cc20335)

### Desktop (please complete the following information):
 - OS: Windows
 - Browser: Opera Gx
 - Version: LVL 5 (core: 102.0.4880.104)

**Comment by jvherck** [comment]
Can you check with the newest version 3.1.2 if this solved your issue? If not, it should now log the error data in the web console. I fixed quite a few bugs with this update, and though I didn't have any trouble signing up new users maybe this update fixed it for you anyway.
